### ISSUE TITLE
Add Agent proxy servers to graph

### ISSUE THREAD

**Issue by vguru1** [rebelinux/Veeam.Diagrammer#16]
I noticed that the report includes code for VMware and HyperV proxies.

Is it possible to add Agent Proxies (the ones needed for File Shares backup in addition to Agent backups)?

**Comment by rebelinux** [comment]
Yes, it is possible.

**Comment by rebelinux** [comment]
File Proxy with protected groups:
![Output](https://github.com/rebelinux/Veeam.Diagrammer/assets/1002783/656fb404-0cc1-4f15-816d-304b6c046e04)

**Comment by rebelinux** [comment]
File Backup Proxy:

![Output](https://github.com/rebelinux/Veeam.Diagrammer/assets/1002783/5b155fa1-b709-49d5-a396-40b0d0153bd7)
