### ISSUE TITLE
Unable to run report

### ISSUE THREAD

**Issue by antdolan** [rebelinux/Veeam.Diagrammer#17]
Running against Veeam 12.1 & PostgreSQL.
Fails when trying to run any combination of the command.  Main difference is it's V12.1 & PostgreSQL.

New-VeeamDiagram -Target SERVER-NAME -Credential $Creds -DiagramType  Backup-to-Repository  -Format pdf,png -Direction top-to-bottom -OutputFolderPath C:\temp\temp -EdgeType polyline -Verbose -EnableEdgeDebug -EnableSubGraphDebug

Graph : Index operation failed; the array index evaluated to null.

Has worked well in past in different environments.  1st time running on 12.1 & PostgreSQL

VERBOSE: Loading module from path 'C:\Program Files\Veeam\Backup and
Replication\Console\Veeam.Backup.PowerShell\..\Veeam.Backup.PowerShell.dll'.
VERBOSE: Trying to import Veeam B&R modules.
VERBOSE: Loading module from path 'C:\Program Files\Veeam\Backup and
Replication\Console\Veeam.Backup.PowerShell\..\Veeam.Backup.PowerShell.dll'.
VERBOSE: Identifying Veeam Powershell module version.
VERBOSE: Using Veeam Powershell module version 11.
VERBOSE: Loading module from path 'C:\Program Files\Veeam\Backup and
Replication\Console\Veeam.Backup.PowerShell\..\Veeam.Backup.PowerShell.dll'.
VERBOSE: Establishing initial connection to Backup Server: XXX .
VERBOSE: Looking for veeam existing server connection.
VERBOSE: No existing veeam server connection found
VERBOSE: Connecting to XXX with XXX credentials
VERBOSE: Validating connection to XXX
VERBOSE: Successfully connected to XXX:9392 Backup Server.
VERBOSE: Operation '' complete.
VERBOSE: Collecting Backup Server information from XXX.
Graph : Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\Veeam.Diagrammer\0.5.3\Src\Public\New-VeeamDiagram.ps1:271 char:18
+ ...      $Graph = Graph -Name VeeamVBR -Attributes $MainGraphAttributes {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Graph], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex,Graph

**Comment by rebelinux** [comment]
Hello,

Can you run the script with the EnableErrorDebug option and send me the output text to: jcolonf@zenprsolutions.com?

Regards.

**Comment by Fr0kh** [comment]
i have the same problem

**Comment by rebelinux** [comment]
I found the bug. The issue will be fixed in the next release.

**Comment by rebelinux** [comment]
Fixed in v0.5.5 please update the module and do the test again.

`update-module -Name Veeam.Diagrammer -force`

**Comment by antdolan** [comment]
works great thank you!
